FROM node:latest

RUN mkdir -p /usr/src/greedy
WORKDIR /usr/src/greedy

ADD ./package.json /usr/src/greedy/package.json

RUN npm install

ADD . /usr/src/greedy
# ADD ./.babelrc /usr/src/wow-frontend/.babelrc
# ADD ./webpack.config.js /usr/src/wow-frontend/webpack.config.js

RUN npm test
